### ISSUE TITLE
Supports Windows 10

### ISSUE THREAD

**Issue by VENTO-off** [dyorgio/run-as-root#2]
Dear dyorgio,
thank you for this interesting library but I have a problem while running a code below:
```
import dyorgio.runtime.run.as.root.RootExecutor;

public class Main {
	
	public static void main(String[] args) {
		try {
			RootExecutor rootExecutor = new RootExecutor("-Xmx64m");
			rootExecutor.run(() -> System.out.println("cd C:/ && mkdir test"));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
```

Output in colsole:
```
'C:\Users\VENTO\AppData\Local\Temp\tmp7523817874742991158run-as-root' is not recognized as an internal or external command,
operable program or batch file.
CODE:1
```

I tried to download source code libraries and now get this error:
```
java.lang.RuntimeException: Class dyorgio.runtime.out.process.OneRunOutProcess does not implement Serializable or externalizable
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:142)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:369)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:664)
	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:546)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:458)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:369)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:664)
	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:546)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:458)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:204)
	at org.nustaq.serialization.FSTConfiguration.asByteArray(FSTConfiguration.java:1161)
	at dyorgio.runtime.out.process.OutProcessUtils.serialize(OutProcessUtils.java:216)
	at dyorgio.runtime.out.process.OneRunOutProcess.call(OneRunOutProcess.java:208)
	at dyorgio.runtime.run.as.root.RootExecutor.execute(RootExecutor.java:116)
	at dyorgio.runtime.run.as.root.RootExecutor.run(RootExecutor.java:86)
	at Main.main(Main.java:8)
```

What I'm doing wrong? Thank you in advance!

**Comment by dyorgio** [comment]
Hi @VENT0, I guess that you are using a new version of OutProcess dependency library.
Can you confirm that? Try with 1.0.0 and let me know if it works.
I will adjust this Library to work with last version of out-process today anyway.

**Comment by dyorgio** [comment]
Done, new version released: 1.1.0.

**Comment by VENTO-off** [comment]
Thank you for your quick answer.
I have updated three libraries - run-as-root, out-process and fast-serialization (by RuedigerMoeller)
and I get new error:
```
'C:\Users\VENTO\AppData\Local\Temp\tmp4421418259955514705run-as-root' is not recognized as an internal or external command,
operable program or batch file.
unable to decode:
java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:249)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1158)
	at dyorgio.runtime.out.process.OutProcessUtils.unserialize(OutProcessUtils.java:228)
	at dyorgio.runtime.out.process.OneRunOutProcess.call(OneRunOutProcess.java:230)
	at dyorgio.runtime.run.as.root.RootExecutor.execute(RootExecutor.java:115)
	at dyorgio.runtime.run.as.root.RootExecutor.run(RootExecutor.java:85)
	at Main.main(Main.java:8)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:296)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readObjectHeaderTag(FSTStreamDecoder.java:98)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:346)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:333)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:313)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	... 6 more
```
Maybe I'm doing wrong something... I have downloaded all these sources of libraries and put them into src folder and ran the program.

**Comment by dyorgio** [comment]
Hi @VENT0, I'm working hard in a version with better support  to Windows OS (including changes in out-process library).
Current release does not works full featured on windows (return code, user cancelation, output console redirection).
I resolved most of all theses problems in my local repo.
My plan is release it in two weeks.

Meanwhile you can solve your problems putting a .cmd extension on temporary file:

```.java
// WinRootProcessManager.java:62
File file = File.createTempFile("tmp", "run-as-root.cmd");
``` 

Related: https://github.com/dyorgio/run-as-root/issues/1

**Comment by VENTO-off** [comment]
Wow, it's very pleasant that you work because of me :)

I change this row and program worked. My code:
```
RootExecutor rootExecutor = new RootExecutor("-Xmx64m");
rootExecutor.run(() -> System.out.println("md c:/test"));
```
But the folder doesn't create... Is there any way to run .jar with admin rights with the help of your library?

**Comment by dyorgio** [comment]
😄 😄 😄 😄 
Look @VENT0, System.out.println() function doesn't execute anything, its just prints argument on system console. like echo in shell. 
In java you can use Runtime.exec to execute external programs, including cmd..
Take a look and good look!
I will keep this issue open until new release.

**Comment by VENTO-off** [comment]
Ok, thank you.
But I try these and nothing happens:
`rootExecutor.run(() -> System.out.println("md c:\\test"));`
`rootExecutor.run(() -> System.out.println("cmd.exe /c md c:\\test"));`
`rootExecutor.run(() -> System.out.println("java -jar Launcher.jar"));`
`rootExecutor.run(() -> System.out.println("cmd.exe /c start java -jar Launcher.jar"));`

**Comment by dyorgio** [comment]
Use  Runtime.exec not System.out.println

**Comment by VENTO-off** [comment]
Sorry, maybe I'm boring you... but I try this:
```
		try {
			RootExecutor rootExecutor = new RootExecutor("-Xmx64m");
			rootExecutor.run(() -> {
				try {
					Runtime.getRuntime().exec("cmd /c start notepad++.exe");
				} catch (IOException e) {
					e.printStackTrace();
				}
			});
		} catch (Exception e) {
			e.printStackTrace();
		}
```
And console output:
```
Requesting administrative privileges...
unable to decode:
java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1137)
	at dyorgio.runtime.out.process.OutProcessUtils.unserialize(OutProcessUtils.java:228)
	at dyorgio.runtime.out.process.OneRunOutProcess.call(OneRunOutProcess.java:230)
	at dyorgio.runtime.run.as.root.RootExecutor.execute(RootExecutor.java:115)
	at dyorgio.runtime.run.as.root.RootExecutor.run(RootExecutor.java:85)
	at Main.main(Main.java:10)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:296)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readObjectHeaderTag(FSTStreamDecoder.java:98)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:344)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
	... 6 more
```

**Comment by dyorgio** [comment]
Hi @VENT0, appears that you are starting to code in Java.
I would like to suggest you to start trying execute no-root commands (without use this lib) first.
When you acomplished that, then wrap command inside rootExecutor.run().
Always start your programs with simple tasks first, make theses tasks works alone, after join all simple working tasks in a big one.
Look for help to use Runtime.exec on stackoverflow or another Java beginer site/blog.
Good luck!

**Comment by dyorgio** [comment]
Hi @VENT0, I think that now this lib works well with Windows machines.
Can you confirm that? (use last version 1.2.0)

**Comment by VENTO-off** [comment]
Wow, thank you very much. I will check it soon.

**Comment by dyorgio** [comment]
Closed by timeout.
