### ISSUE TITLE
class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by jflefebvre06** [dyorgio/run-as-root#3]
Hello,

Failed to use run-as-root api.

`new RootExecutor("-Xmx64m")` throws

```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at dyorgio.runtime.out.process.OutProcessUtils.getCurrentClasspath(OutProcessUtils.java:83)
	at dyorgio.runtime.out.process.OneRunOutProcess.<init>(OneRunOutProcess.java:163)
	at dyorgio.runtime.out.process.OneRunOutProcess.<init>(OneRunOutProcess.java:133)
	at dyorgio.runtime.out.process.OneRunOutProcess.<init>(OneRunOutProcess.java:112)
	at dyorgio.runtime.out.process.OneRunOutProcess.<init>(OneRunOutProcess.java:93)
	at dyorgio.runtime.run.as.root.RootExecutor.<init>(RootExecutor.java:72)
```

I m using JDK 11

**Comment by dyorgio** [comment]
Hello @jflefebvre06, I adjusted out-process lib to be compatible with Java11+ releases.
Can you include specific version (1.2.3) of this dependency in your project and tell us if it works?
```pom.xml
<dependency>
    <groupId>com.github.dyorgio.runtime</groupId>
    <artifactId>out-process</artifactId>
    <version>1.2.3</version>
</dependency>
```

**Comment by jflefebvre06** [comment]
Works fine thank you @dyorgio 

Could you please release `run-as-root` with this new dependency ?

**Comment by dyorgio** [comment]
@jflefebvre06 done!, version 1.2.1 is using last out-process version too.
