### ISSUE TITLE
ClassNotFoundException when trying to use

### ISSUE THREAD

**Issue by abandonedaccount6235** [dyorgio/run-as-root#5]
With this code:
```
    override fun inject(tabPane: TabPane) {
        tabPane.apply {
            tab("Test") {
                button("Test") {
                    action {
                        println("Running action runner")
                        ActionRunner.runActions("yeet")
                    }
                }
            }
        }
    }
```
I get this exception:
```
java.security.PrivilegedActionException: java.util.concurrent.ExecutionException: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1$1 loader:jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:395)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1$1 loader:jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
	at dyorgio.runtime.out.process.OneRunOutProcess.call(OneRunOutProcess.java:276)
	at dyorgio.runtime.run.as.root.RootExecutor.execute(RootExecutor.java:115)
	at dyorgio.runtime.run.as.root.RootExecutor.run(RootExecutor.java:85)
	at com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1.invoke(PluginView.kt:17)
	at com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1.invoke(PluginView.kt:8)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt:426)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	... 9 more
Caused by: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1$1 loader:jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1158)
	at dyorgio.runtime.out.process.OutProcessUtils.unserialize(OutProcessUtils.java:270)
	at dyorgio.runtime.out.process.entrypoint.OneRunRemoteMain.main(OneRunRemoteMain.java:58)
Caused by: java.lang.RuntimeException: class not found CLASSNAME:com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1$1 loader:jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235)
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190)
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:173)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:478)
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:939)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:347)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.pikachu.mycompany.views.PluginView$root$1$1$1$1$1$1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:197)
	... 14 more
```
when I click the button (run the code)

**Comment by dyorgio** [comment]
You have a lot of inner and anonymous classes involved, remember that to transfer code to an external process is necessary to serialize objects and classes....
Try to create concrete classes for all your run-as-root commands.
Start doing simple things first (in a simple class with main method), then, after it works, transfer to your final code.

**Comment by abandonedaccount6235** [comment]
I went back and tried that (keeping code in a simple class) and got this exception: https://hasteb.in/fifeveza.pl
This is my code:
```
package com.pikachu.sccm.data;

import dyorgio.runtime.run.as.root.RootExecutor;

import java.io.IOException;

public final class ActionRunner {

    public static void runActions(String computer)  throws Exception {
        var executor = new RootExecutor();
        var str = "str";
        executor.run(() -> System.out.println("Cool " + str));
    }

    public static void normalMethod() {
        System.out.println("thing");
    }

}
```
and my call:
```
    override fun inject(tabPane: TabPane) {
        tabPane.apply {
            tab("Software Center") {
                button("Test") {
                    action {
                        println("Running action runner")
                        ActionRunner.normalMethod()
                        ActionRunner.runActions("yeet")
                    }
                }
            }
        }
    }
```

**Comment by dyorgio** [comment]
As you see in stacktrace, com.pikachu.sccm.data.ActionRunner cannot be found by external JVM.

Recently I made some changes in out-process lib to support Java11+, but in fact you added another variable in this equation: Kotlin.

Your problem is relative with classpaths, and it can be relative with many things (Kotlin runtime, IDE, out-process incompatibility).

Please, insert this code BEFORE ActionRunner.runActions call and tell us if ActionRunner classpath is present:

```java
println("CLASSPATH USED BY JVM:"+ OutProcessUtils. getCurrentClasspath())
```

**Comment by abandonedaccount6235** [comment]
thanks for the help... Here's the code I used:
```
    override fun inject(tabPane: TabPane) {
        tabPane.apply {
            tab("Software Center") {
                button("Test") {
                    action {
                        println("Running action runner")
                        ActionRunner.normalMethod()
                        println("CLASSPATH USED BY JVM:" + OutProcessUtils.getCurrentClasspath())
                        ActionRunner.runActions("yeet")
                    }
                }
            }
        }
    }
```
and the output:
```
CLASSPATH USED BY JVM:M:\MyCompanyFramework\build\classes\java\main;M:\MyCompanyFramework\build\classes\kotlin\main;M:\MyCompanyFramework\build\resources\main;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\com.beust\klaxon\5.0.1\4c1ffe12cd890eef021808dfb2fe2993dfeaf0c9\klaxon-5.0.1.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\no.tornado\tornadofx\1.7.19\fdd74beea0e573461c6657f5937eb3f47a739c52\tornadofx-1.7.19.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\com.opencsv\opencsv\5.0\6aa7ff327f0ad7e3e9dabd6fe29ee19122b382c3\opencsv-5.0.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\com.github.dyorgio.runtime\run-as-root\1.2.1\22fc791c456c4931c1e5c4e2e571e0a04d1e40a\run-as-root-1.2.1.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.3.41\77652607ed82a49202d8a0b89de16994b61bdd75\kotlin-stdlib-jdk8-1.3.41.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.3.20\cd49eec32cf964333faf59e04b4085eac7008477\kotlin-reflect-1.3.20.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.3.41\a1f331124ba069a09e964ad2640c36f140f2c758\kotlin-stdlib-jdk7-1.3.41.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.3.41\e24bd38de28a326cce8b1f0d61e809e9a92dad6a\kotlin-stdlib-1.3.41.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.glassfish\javax.json\1.1.2\a507518970d55e9de24665af06d70aae91b4aaa1\javax.json-1.1.2.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-text\1.7\4d7d6dc210f80d0bff18645cc534a0c45324d0d6\commons-text-1.7.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.9\122c7cee69b53ed4a7681c03d4ee4c0e2765da5\commons-lang3-3.9.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\commons-beanutils\commons-beanutils\1.9.4\d52b9abcd97f38c81342bb7e7ae1eee9b73cba51\commons-beanutils-1.9.4.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-collections4\4.4\62ebe7544cb7164d87e0637a2a6a2bdc981395e8\commons-collections4-4.4.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\com.github.dyorgio.runtime\out-process\1.2.3\dc67b881f4699321635dd0b631307107e6895f90\out-process-1.2.3.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\javax.json\javax.json-api\1.1.2\b38c52a6e180359108bd5e35dbeec7d1be45c535\javax.json-api-1.1.2.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.2\4bfc12adfe4842bf07b657f0369c4cb522955686\commons-logging-1.2.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\commons-collections\commons-collections\3.2.2\8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5\commons-collections-3.2.2.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\de.ruedigermoeller\fst\2.57\70583ffcab07a0c756428811dd108a342b575d2e\fst-2.57.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.3.41\2ecf4aa059427d7186312fd1736afedf7972e7f7\kotlin-stdlib-common-1.3.41.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.8.8\d478fb6de45a7c3d2cad07c8ad70c7f0a797a020\jackson-core-2.8.8.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.javassist\javassist\3.21.0-GA\598244f595db5c5fb713731eddbb1c91a58d959b\javassist-3.21.0-GA.jar;C:\Users\MyUser\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\2.5.1\272bab9a4e5994757044d1fc43ce480c8cb907a4\objenesis-2.5.1.jar
unable to decode: 3dyorgio.runtime.run.as.root.RootExecutor$RemoteCall  !java.lang.invoke.SerializedLambdaB� com.
```
plus a stacktrace like before

**Comment by abandonedaccount6235** [comment]
it may be relevant that I am loading these plugins (where the call is) at runtime:
```
    private fun loadJar(jar: URL) : Plugin {
        val loader = URLClassLoader(arrayOf(jar), Plugins.javaClass.classLoader)
        val details = getPluginDetails(loader)
        val mainClass = loader.loadClass(details.main)
        check(Plugin::class.java.isAssignableFrom(mainClass)) { "$mainClass doesn't implement ${Plugin::class}" }
        val pluginConstructor = mainClass.getConstructor(Plugin.Details::class.java, PluginState::class.java)
        return pluginConstructor.newInstance(details, PluginState.PENDING_LOAD) as Plugin
    }

    fun load(args: Array<String>): CompletableFuture<Void> {
        check(PLUGINS.isEmpty()) { "Plugins already loaded" }

        val loadController = PluginLoadController()

        val loadingPlugins = getPluginJars()
            .map { loadJar(it) }
            .map {

                try {
                    Files.createDirectories(PLUGIN_PATH.resolve(it.details.name))
                } catch (e: FileAlreadyExistsException) {}

                it.state = PluginState.LOADING
                it.load(args, PLUGIN_LOAD_POOL).thenRun {
                    it.state = PluginState.LOADED
                    PLUGINS.add(it)
                    loadController.fireLoadEvent(it)
                }
            }
            .toArray { arrayOfNulls<CompletableFuture<Void>>(it)}

        return CompletableFuture.allOf(*loadingPlugins)

    }
```

**Comment by dyorgio** [comment]
Yes, it is very relevant...
Try duplicate RootExecutor class in your project and modify constructor to pass classpath to OneRunOutProcess instance:
```java
public RootExecutor(String... javaOptions) throws IOException {
        this.outProcess = new OneRunOutProcess(MANAGER, YOUR_CUSTOM_CLASSPATH + File.pathSeparator + OutProcessUtils.getCurrentClasspath(), javaOptions);
    }
```

Take a look in OutProcessUtils.generateClassPath method, it maybe can help you.

**Comment by abandonedaccount6235** [comment]
i never got this working even when using just java unfortunately:
```
package root;

import dyorgio.runtime.run.as.root.RootExecutor;

public class RunAsRoot {

    public static void main(String[] args) throws Throwable {
        RootExecutor executor = new RootExecutor();
        System.out.println("Int is: " + executor.call(OtherClass::getInt));
    }

}
```
```
package root;

public class OtherClass {

    public static int getInt() {
        return 1;
    }

}
```
Outputs: `Int is: null`

**Comment by dyorgio** [comment]
Hi @Pikachu920, I run this code without issues here.
To be more productive, please, attach a zip file with a complete project folder (IDE/gradle files simulating this result)  and tell me what version of Java and IDE you are using.

**Comment by dyorgio** [comment]
@Pikachu920, Any news? I made an update on out-process lib (1.2.5) that fixes some issues with paths, try out.

**Comment by abandonedaccount6235** [comment]
sorry for the late response, unfortauntely it does not. i'm targeting java 8 and use intellij

**Comment by abandonedaccount6235** [comment]
`null woah!!` results from:
```
public class ActionRunner {

    public static void runActions(String computer, Action... actions) throws Exception {
        RootExecutor executor = new RootExecutor("-Xmx640m");
        System.out.println(executor.call(() -> 1 + 6) + " woah!!");
        executor.run(() -> {
            SCCMPlugin.Companion.runActions(computer, actions);
        });
    }

}
```
the jar this class is in is still being loaded at runtime, and is being called from Kotlin.
also, i do get the UAC prompt

**Comment by dyorgio** [comment]
hi @Pikachu920 my results for this code:
```java
import dyorgio.runtime.run.as.root.RootExecutor;

public class TestMain {

    public static void main(String[] args) throws Exception {
        RootExecutor executor = new RootExecutor("-Xmx640m");
        System.out.println(executor.call(() -> 1 + 6) + " woah!!");
    }
}
```
Was...
```
--- exec-maven-plugin:1.5.0:exec (default-cli) @ working ---

7 woah!!
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 4.624 s
```

I really think that kotlin is the problem, but I'm not a kotlin developer, so I need a favor, please create a basic kotlin project (<s>glade</s> gradle or maven) with same class and result and attach here.

With this I can reproduce and fix.

**Comment by abandonedaccount6235** [comment]
definitely. i'll work on a project. i did have this same problem with java so i will try to make it with both.

also - when you say glade did you mean gradle? that's what i typically use

**Comment by dyorgio** [comment]
>  when you say glade did you mean  gradle?

Yes 😄, sorry

**Comment by abandonedaccount6235** [comment]
https://anonfile.com/L3cbRcW8n0/TestRoot_zip

Both projects (kotlin and java) in that zip result in `Addition result: null`

**Comment by abandonedaccount6235** [comment]
@dyorgio did these projects help at all?

**Comment by dyorgio** [comment]
Hi @Pikachu920, they runned without issues here (in recent macos update [aka. Catalina] I needed to give to java executable full disk access).
I will take some time to try to reproduce on this weekend... Tell me more details about you env: OS, version, Java Provider, Java version. I will made a VM and try again.

**Comment by abandonedaccount6235** [comment]
Java:
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) Client VM (build 25.202-b08, mixed mode)
```
OS:
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763
```

**Comment by dyorgio** [comment]
Hello @Pikachu920, I have good and bad news:
I can't reproduce your problem, everything works here:
```
Executing: gradle :run
Arguments: [-PmainClass=com.test.root.Main, -PcmdLineArgs=, -PjvmLineArgs=, -c, C:\Users\activities\Documents\NetBeansProjects\JavaRoot\settings.gradle]

> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :run
Addition result: 5

BUILD SUCCESSFUL in 22s
2 actionable tasks: 1 executed, 1 up-to-date
```

Did your windows showing this dialog? (in your language, of course):
<img width="499" alt="Captura de Tela 2020-02-22 às 10 53 02" src="https://user-images.githubusercontent.com/1438251/75093588-d7dd1380-5561-11ea-9f8a-1be07b20d8b7.png">

**Comment by abandonedaccount6235** [comment]
good news - i figured out what is breaking it. The issue reproduces when the code is run from a network drive. I can copy the same jar onto a local drive and the code correctly does the addition. I did a bit of basic research and it seems like the problem is the `-cp` argument does not work with network mounts unless you specify the full UNC path (e.g. `\\computer\share\folder` rather than a mapped `M:\folder`). Currently, `run-as-root` uses the local mapped path instead of expanding it to the full UNC path.

**Comment by abandonedaccount6235** [comment]
Created a new issue #6 about the network path thing since this issue is kinda offtopic now. I also tried the kotlin project and it also runs fine when on a local drive.
