### ISSUE TITLE
In-memory only class access

### ISSUE THREAD

**Issue by abandonedaccount6235** [dyorgio/run-as-root#7]
Sorry to keep bothering you, but I am now having trouble accessing classes loaded via a URLClassLoader. [Here](https://github.com/dyorgio/run-as-root/files/4282317/RuntimeLoad.zip) is a test Gradle project that loads a jar from a child project which tries to call one of it's own methods as root. Compiling the main `RuntimeLoad` project will set up the child project appropriately. I get this result on my machine:
```
M:\Projects\TestRoot\RuntimeLoad\build\libs>java -jar RuntimeLoad-1.0-SNAPSHOT.jar
From the main jar:
main jar: 5

Now from the child:
M:\Projects\TestRoot\RuntimeLoad\Child\build
Does the child jar exist? true
Clazz is: com.test.child.Child
unable to decode: 3dyorgio.runtime.run.as.root.RootExecutor$RemoteCall? !java.lang.invoke.SerializedLambdaB² com.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.test.runtime.Main.main(Main.java:32)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.test.child.Child loader:sun.misc.Launcher$AppClassLoader@4e25154f
        at dyorgio.runtime.out.process.OneRunOutProcess.call(OneRunOutProcess.java:277)
        at dyorgio.runtime.run.as.root.RootExecutor.execute(RootExecutor.java:115)
        at dyorgio.runtime.run.as.root.RootExecutor.call(RootExecutor.java:100)
        at com.test.child.Child.invokeMe(Child.java:11)
        ... 5 more
Caused by: java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.test.child.Child loader:sun.misc.Launcher$AppClassLoader@4e25154f
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
        at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1158)
        at dyorgio.runtime.out.process.OutProcessUtils.unserialize(OutProcessUtils.java:320)
        at dyorgio.runtime.out.process.entrypoint.OneRunRemoteMain.main(OneRunRemoteMain.java:58)
Caused by: java.lang.RuntimeException: class not found CLASSNAME:com.test.child.Child loader:sun.misc.Launcher$AppClassLoader@4e25154f
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:235)
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:190)
        at org.nustaq.serialization.coders.FSTStreamDecoder.classForName(FSTStreamDecoder.java:483)
        at org.nustaq.serialization.FSTObjectInput.getClassForName(FSTObjectInput.java:204)
        at org.nustaq.serialization.serializers.FSTClassSerializer.instantiate(FSTClassSerializer.java:57)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadWithSer(FSTObjectInput.java:501)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
        at org.nustaq.serialization.FSTObjectInput.readObjectCompatibleRecursive(FSTObjectInput.java:635)
        at org.nustaq.serialization.FSTObjectInput.readObjectCompatible(FSTObjectInput.java:574)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:559)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
        at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
        at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
        at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.test.child.Child
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.nustaq.serialization.FSTClazzNameRegistry.classForName(FSTClazzNameRegistry.java:197)
        ... 20 more
```

Environment:
Java:
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) Client VM (build 25.202-b08, mixed mode)
```
OS:
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763
```

**Comment by dyorgio** [comment]
@Pikachu920 , I tried to download your file many times, no luck.
Please, stop to use anothers sites to upload (worms, scams, spams and virus).
Just drop files here and I can download it to help you.

**Comment by abandonedaccount6235** [comment]
[RuntimeLoad.zip](https://github.com/dyorgio/run-as-root/files/4282317/RuntimeLoad.zip)

sorry, it's only one of the sites that isn't blocked here and I didn't realize github supported file uploads.

**Comment by abandonedaccount6235** [comment]
maybe the answer is agents? i'm thinking maybe instead of using the `-cp` argument, it's possible to start a new JVM that attaches an agent to the existing JVM and grabs the bytecode of the classes it needs to and then defines those in the new jvm?

**Comment by dyorgio** [comment]
Hi @Pikachu920, it is a classpath problem again.
Saddly current run-as-root implementation always use current-classpath to provide classpath to new JVM.
I'm adding in next version a way to pass your custom classpath to RootExecutor constructor. 

Please, add attached class to your child project, use it to pass classpath to RootExecutor new constructor:
[RootExecutor.java.zip](https://github.com/dyorgio/run-as-root/files/4283608/RootExecutor.java.zip)

```java
// Child.java
public class Child {

    public static void invokeMe(String classpath) throws Throwable {
        System.out.println("child classpath: " + classpath);
        RootExecutor e = new RootExecutor((File) null, classpath);
        System.out.println("child result: " + e.call(() -> 1 + 9));
    }
}
```
And in your Main.java:
```java
clazz.getDeclaredMethod("invokeMe", String.class).invoke(null, p.toString() + File.pathSeparator + OutProcessUtils.getCurrentClasspath() );
```

**Comment by abandonedaccount6235** [comment]
I'll try that. do you think that the agent approach is worth trying?

**Comment by dyorgio** [comment]
I don't think so, by two reasons:
1) Java agents needs bootstrap classpath too (same problem)
2) Automate root execution configuration can be dangerous.

Maybe you can stop to create instances of RootExecutor on child projects...
Why not always create it in main project? than you will have total control over it.

**Comment by abandonedaccount6235** [comment]
correct me if i'm wrong however the main project would not solve the problem as the code i'm trying to run. and putting plugin-specific code in the main project defeats the purpose of a plugin

**Comment by dyorgio** [comment]
If run as root is/can only on plugins you are right.
But also, plugins normally have deps in host module (some interface or way-to-work).
Can I close this issue? Appears that discussion is not more about a problem in lib :).

**Comment by abandonedaccount6235** [comment]
go for it

**Comment by dyorgio** [comment]
Nice,  I will make a release on the weekend ;)
